export const websiteRoutes = {
  home: "/",
  about: "/about",
  contact: "/contact",
  privacyPolicy: "/privacy-policy",
  helpCenter: "/help-center",
  purchaseProtection: "/purchase-protection",
  chat: "/chat",
  termsAndConditions: "/terms-conditions",
  pricingPlans: "/pricing-plans",
  cart: "/cart",
  compare: "/compare",
  shorts: "/short",
  checkout: "/checkout",
  faq: "/faq",
  refundPolicy: "/refund",
  invoice: "/invoice",
  userLogin: "/user/login",
  userRegister: "/user/signup",
  userOtp: "/user/otp",
  userForgotPassword: "/forgot-password",
  userChangePassword: "/change-password",
  sellerLogin: "/seller/login",
  sellerSignup: "/seller/signup",
  sellerOtp: "/seller/otp",
  sellerForgotPassword: "/seller/forgot-password",
  sellerChangePassword: "/seller/change-password",
  resellerLogin: "/reseller/login",
  resellerSignup: "/reseller/signup",
  resellerOtp: "/reseller/otp",
  resellerForgot: "/reseller/forgot-password",
  resellerChangePassword: "/reseller/change-password",
  productListing: "/product",
  productDetails: "/product/:url",
  sellerListing: "/seller",
  sellerDetails: "/seller/:url",
  sundaybazarListing: "/sunday-bazar",
  sundaybazarCategoryListing: "/sunday-bazar/category",
  sundaybazarDetails: "/sunday-bazar/:url",
  resellerListing: "/reseller",
  properties: "/property",
  vehicleListing: "/vehicle",
  vehicleDetail: "/vehicle/:id",
  category: "/category/:url",
  subCategory: "/subcategory/:url",
  reseller: "/reseller/:url",
  resellerHire: "/reseller/:url/hire",
  searchResult: "/search-results",
  propertyDetail: "/property/:id",
  login: "/login"
};

export const userDashboardRoutes = {
  dashboard: "/dashboard/user",
  home: "home",  
  profile: "profile",
  order: "order",
  orderTrack: "order/:id/track",
  orderInfo: "order/:id/info",
  orderInvoice: "order/:id/invoice",
  reviewProduct: "order/cart/:code/review",
  wishlist: "wishlist",
  userHire:"hire/:status",
  hireDetail: "hire/:status/:code",
  userProduct: "product",
  settings: "settings",
  support: "support",
  addSupport: "support/add",
  chat: "chat",
  follow: "follow"
};


export const sellerDashboardRoutes = {
  dashboard: "/dashboard/seller",
  home: "home",
  category: "category",
  inventory: "inventory",
  addInventory: "inventory/add",
  product: "product",
  addProduct:"product/add",
  editProduct: "product/:url/edit",
  productVideo: "product/:url/video",
  productFiles: "product/:url/files",
  vehicle: "vehicle",
  addVehicle: "vehicle/add",
  editVehicle: "vehicle/:id/edit",
  vehicleFiles: "vehicle/:id/files",
  vehicleVideo: "vehicle/:id/video",
  vehicleFeatures: "vehicle/:id/features",
  bazar: "sunday-bazar",
  order: "order",
  orderInfo: "order/:id/info",
  orderInvoice: "order/:id/invoice",
  video: "video",
  package: "package",
  settings: "setting",
  chat: "chat",
  follow: "follow",
  brand: "brand",
  addBrand:"brand/add",
  support: "support",
  addSupport: "support/add",
  streaming: "streaming",
  addStreaming: "streaming/add",
  sellerStreaming: "streaming/:url",
  streamingInfo: "streaming/:url/info",
  propertyListing:"property",
  propertyadd:"property/add",
  propertyVideo:"property/:id/video",
  propertyFiles:"property/:id/files",
  propertyEdit:"property/:id/edit",
  propertyAmenities:"property/:id/amenities",
};

export const resellerDashboardRoutes = {
  dashboard: "/dashboard/reseller",
  home: "home",
  product: "product",
  productVideo: "product/:url/video",
  productFiles: "product/:url/files",
  productEdit: "product/:url/edit",
  inventry: "inventory",
  addInventory: "inventory/add",
  addProduct: "hire/:code/product",
  hire: "hire/:status",
  hireDetail:"hire/:status/:code",
  settings: "setting",
  support: "support",
  addSupport: "support/add",
  chat: "chat",
  follow: "follow",
  streaming: "streaming",
  addStreaming: "streaming/add",
  resellerStreaming:"streaming/:url",
  streamingInfo:"streaming/:url/info"
};

export const recoverRoutes = {
  user: "/user/recover/:token",
  seller: "/seller/recover/:token",
  reseller: "/reseller/recover/:token"
}
